####
##
## CircuitSetup Security+ Garage Door Opener
## Firmware configuration for ESPHome
##
## filename: circuitsetup-gdo-dry-contact.yaml
## GitHub: https://github.com/circuitsetup/circuitsetup-esphome
##
## Copyright© 2023 Konnected Inc.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
## files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, 
## modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
## is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE 
## LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR 
## IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##
####

####
# INTRODUCTION
# 
# This ESPHome based firmware configuration is designed for the CircuitSetup Security+ Garage Door Opener which is built on the ESP32-S3.
# The Garage Door Opener retrofits an older style traditional garage door opener with a dry-contact trigger and has the
# following features which are included as packages below:
#
# 1. Wired contact sensor for detecting open/closed state of garage door
# 2. Emulates a garage door opener button wired to a dry contact relay to open/close the garage door.
# 3. Adds a Garage Door "Cover" entity that is exposed to Home Assistant. The cover entity incorporates the state of the 
#    garage door and controls to open/close/stop it.
# 4. Flashes an onboard LED and beeps an onboard piezo sounder as a warning before automatically closing.
# 5. Provides garage temp and humidity

####
# GENERAL SETTINGS
# Customize these variables to your preferences and needs
# more: https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  ####
  # NAME
  # By default, the name of the ESPHome device is "circuitsetup-gdo-xxxxxx" where xxxxxx is a unique identifier. The device's
  # hostname on your network is also defined by the name, defaulting to "circuitsetup-xxxxxx.local". Edit this variable to
  # customize the name and hostname. Note: only lowercase characters, numbers and hyphen(-) are allowed.
  name: circuitsetup-gdo
  friendly_name: Garage Door Opener
  project_name: circuitsetup.gdo-dry-contact
  project_version: "1.0"
  garage_door_cover_name: Garage Door
  garage_temp_name: Garage Temp
  garage_humidity_name: Garage Humidity
  temp_update_interval: 60s
  temp_adjust: "0.8825" # 1-0.1175 - 11.75% decrease
  dew_point_offset: "1.3" # Offset in °F to correct sensor's lower dew point read

  ####
  # GARAGE DOOR OPENER MOMENTARY DURATION
  # Duration to make the relay contact closure for the garage door opener button circuit. 
  garage_door_opener_momentary_duration: 300ms

  ####
  # GARAGE DOOR CLOSE WARNING DURATION
  # Duration to blink the warning LED and beep the buzzer before the garage door closes.
  garage_door_close_warning_duration: 5s

  ####
  # ADDITIONAL SETTTINGS
  sensor_debounce_time: 200ms
  blink_on_state: "true"

  ####
  # INTERNAL MAPPINGS
  # DO NOT EDIT these when using circuitsetup hardware
  door_control_pin: GPIO7 # Aux Out
  wired_sensor_pin: GPIO5 # Aux In 1
  warning_beep_pin: GPIO4
  warning_leds_pin: GPIO3
  status_led: GPIO18
  sda: GPIO16
  scl: GPIO15

####
# PACKAGES
# Each package includes a Garage Door Opener feature described
# Remove or comment out any packages that you do not need or want.
packages:

  remote_package:
    url: https://github.com/circuitsetup/circuitsetup-esphome
    ref: master
    refresh: 1d
    files:

      ####
      # CORE
      # This package is required and sets up core ESPHome features.
      - packages/core-esp32-s3.yaml

      ####
      # GARAGE DOOR WIRED SENSOR
      # Enables a wired contact sensor for reporting the open or closed state of the garage door
      # via the physical INPUT terminals.
      - packages/garage-door-wired-sensor.yaml

      ####
      # GARAGE DOOR COVER
      # The Garage Door Cover is the main user interface entity representing a garage door in Home Assistant.
      # more: https://www.home-assistant.io/integrations/cover/
      # WIRED SENSOR 
      - packages/garage-door-cover-wired.yaml

      ####
      # GARAGE DOOR OPENER BUTTON
      # Enables the garage door opener relay labeled DOOR on the CircuitSetup Garage Door Opener as a button entity. When
      # pressed, the relay will close the dry contact, simulating a physical press of the garage door opener wall button.
      - packages/garage-door-opener-button.yaml

      ####
      # WARNING LED
      # Enables the onboard warning LED light, with strobe effect. Used to visually warn of garage door automatic closing.
      # warning_led: !include packages/warning-led.yaml
      - packages/warning-led.yaml

      ####
      # WIFI
      # Enables WiFi connectivity and diagnostics. Uncommet below to enable WiFi.
      # wifi: !include packages/wifi.yaml
      - packages/wifi-esp32.yaml

      ####
      # PRE-CLOSE WARNING
      # Enables a pleasant and customizable pre-close warning tone  using the onboard piezo buzzer. Used to audibly 
      # warn of a garage door automatic closing.    
      - packages/buzzer-rtttl.yaml
      - packages/pre-close-warning-tones.yaml

      ####
      # STATUS LED
      # Enables the onboard blue status LED as an activity/error indicator
      # status_led: !include packages/status-led.yaml
      - packages/status-led.yaml
      
      ####
      # TEMP SENSOR
      # The on-board temp & humidity sensor
      - packages/temp-sensor.yaml

####
# DASHBOARD IMPORT
# Enables automatic discovery and upgrades via ESPHome Dashboard
# more: https://esphome.io/guides/getting_started_hassio.html
dashboard_import:
  package_import_url: github://CircuitSetup/circuitsetup-esphome/circuitsetup-gdo-dry-contact.yaml@master
  import_full_config: false

#### 
# LOGGER
# more: https://esphome.io/components/logger.html
logger:
  level: DEBUG
  logs:
    ledc.output: INFO
    sensor: INFO
    json: INFO
    api: DEBUG

####
# NATIVE API
# Enables the native ESPHome API
# more: https://esphome.io/components/api.html
api:

esp32_improv:
  authorizer: none

web_server:
