# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  name: garage-door
  garage_door_opener_momentary_duration: 500ms

esphome:
  name: $name
  name_add_mac_suffix: true
  platform: ESP8266
  board: nodemcuv2
  project:
    name: konnected.garage-door-esp8266
    version: "0.1.0"

####
# DASHBOARD IMPORT
# Enables automatic discovery and upgrades via ESPHome Dashboard
# more: https://esphome.io/guides/getting_started_hassio.html
dashboard_import:
  package_import_url: github://konnected-io/konnected-esphome/garage-door-esp8266.yaml@master
  import_full_config: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

improv_serial:

captive_portal:

####
# PACKAGES
# The packages included below add functionality to your Konnected Garage Door opener device.
# Depending on your connected hardware and setup, you may want to customize or add/remove packages
# to configure your garage door opener to meet your needs. Comment (or remove) packages that you don't
# need or want.
packages:

  ####
  # GARAGE DOOR WIRED SENSOR
  # Enables a wired contact sensor for reporting the open or closed state of the garage door
  # via the physical INPUT terminals.
  garage_door_wired_sensor: !include packages/garage-door-wired-sensor.yaml

  ####
  # GARAGE DOOR OPENER BUTTON
  # Enables the garage door opener relay labeled DOOR on the Konnected Garage Door Opener as a button entity
  garage_door_opener_button: !include packages/garage-door-opener-button.yaml

  ####
  # STROBE
  # Enables 12V switched output labeled STR on the Konnected Garage Door opener as a switch entity
  garage_door_strobe: !include packages/garage-door-strobe.yaml

light:
  - id: led_light
    platform: binary
    name: "Warning LED"
    output: warning_led_output
    effects:
      - strobe:

  - id: buzzer
    platform: binary
    output: buzzer_output
    effects:
      - strobe:
          colors:
            - state: true
              duration: 80ms
            - state: false
              duration: 100ms  
    internal: true  

output:
  - id: warning_led_output
    platform: gpio
    pin: D7

  - id: buzzer_output
    platform: gpio
    pin: D8  
    
cover:
  - platform: template
    name: Garage Door
    device_class: garage
    lambda: |-
      if (id(garage_door_wired_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - button.press: garage_door_opener_button
    close_action:
      - light.turn_on:
          id: led_light
          effect: strobe
      - light.turn_on:
          id: buzzer
          effect: strobe
      - delay: 5s
      - button.press: garage_door_opener_button
    stop_action:
      - button.press: garage_door_opener_button
    on_closed:
      - light.turn_off: led_light
      - light.turn_off: buzzer

i2c:
  scan: True

sensor:
  - platform: vl53l0x
    name: Distance
    update_interval: 5s
    long_range: true
    accuracy_decimals: 1

  - platform: wifi_signal
    name: WiFi Signal
    id: wifi_signal_db
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: Signal %
    entity_category: diagnostic


text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: diagnostic
  
    

    
