esphome:
  platformio_options:
    lib_deps:
      - https://github.com/CircuitSetup/gdolib.git#09f439db9ff8fde51f4de5d5686a9647ddb8ecd6

secplus_gdo:
  id: cs_gdo
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
  auto_start: true
  min_command_interval: 50ms
  sync_retry_interval: 30s

light:
  - platform: secplus_gdo
    id: gdo_light
    secplus_gdo_id: cs_gdo
    name: ${garage_light_name}

cover:
  - platform: secplus_gdo
    id: gdo_door
    secplus_gdo_id: cs_gdo
    name: ${garage_door_cover_name}

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_openings
    type: openings
    name: ${garage_openings_name}

text_sensor:
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_battery
    type: battery
    name: ${garage_battery_name}
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_protocol_text
    type: protocol
    name: Security+ Protocol

lock:
  - platform: secplus_gdo
    id: gdo_lock_remotes
    secplus_gdo_id: cs_gdo
    name: ${garage_lock_name}

binary_sensor:
  - platform: secplus_gdo
    name: ${garage_motion_name}
    id: gdo_motion
    secplus_gdo_id: cs_gdo
    type: motion
  - platform: secplus_gdo
    name: ${garage_obstruction_name}
    id: gdo_obst
    secplus_gdo_id: cs_gdo
    type: obstruction
  - platform: secplus_gdo
    name: ${garage_motor_name}
    id: gdo_motor
    secplus_gdo_id: cs_gdo
    type: motor
  - platform: secplus_gdo
    name: ${garage_button_name}
    id: gdo_button
    secplus_gdo_id: cs_gdo
    type: button
  - platform: secplus_gdo
    name: ${garage_wireless_remote_name}
    id: gdo_wireless_remote
    secplus_gdo_id: cs_gdo
    type: wireless_remote
  - platform: secplus_gdo
    name: ${garage_sync_name}
    id: gdo_synced
    secplus_gdo_id: cs_gdo
    type: sync

switch:
  - platform: secplus_gdo
    id: gdo_learn
    type: learn
    secplus_gdo_id: cs_gdo
    name: Learn
  - platform: secplus_gdo
    id: gdo_toggle_only
    type: toggle_only
    secplus_gdo_id: cs_gdo
    name: Toggle Only

select:
  - platform: secplus_gdo
    id: gdo_protocol
    secplus_gdo_id: cs_gdo
    name: Security+ Protocol

number:
  - platform: secplus_gdo
    name: Opening Duration
    secplus_gdo_id: cs_gdo
    id: gdo_open_duration
    type: open_duration
    unit_of_measurement: "ms"
    internal: true

  - platform: secplus_gdo
    name: Closing Duration
    secplus_gdo_id: cs_gdo
    id: gdo_close_duration
    type: close_duration
    unit_of_measurement: "ms"
    internal: true

  - platform: secplus_gdo
    name: Client ID
    secplus_gdo_id: cs_gdo
    id: gdo_client_id
    type: client_id
    internal: true

  - platform: secplus_gdo
    name: Rolling Code
    secplus_gdo_id: cs_gdo
    id: gdo_rolling_code
    type: rolling_code
    internal: true

button:
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_sync
    type: sync
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_resync
    type: resync
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_restart_comms
    type: restart_comms
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_reset_travel
    type: reset_travel_timings
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_door_toggle
    type: door_toggle
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_light_toggle
    type: light_toggle
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_lock_toggle
    type: lock_toggle
  - platform: factory_reset
    name: Factory Reset
    id: hard_reset
    entity_category: config
