text_sensor:
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_last_error
    type: last_error
    name: Last Error

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_last_event
    type: last_event
    name: Last Event

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_opener_id
    type: opener_id
    name: Last Opener ID

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_gdolib_version
    type: gdolib_version
    name: gdolib Version

sensor:
  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_paired_total
    type: paired_devices_total
    name: Paired Devices Total

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_paired_remotes
    type: paired_devices_remotes
    name: Paired Remotes

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_paired_keypads
    type: paired_devices_keypads
    name: Paired Keypads

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_paired_wall_controls
    type: paired_devices_wall_controls
    name: Paired Wall Controls

  - platform: secplus_gdo
    secplus_gdo_id: cs_gdo
    id: gdo_paired_accessories
    type: paired_devices_accessories
    name: Paired Accessories
