substitutions:
  name: gdo-advanced
  friendly_name: GDO Advanced
  project_name: circuitsetup.secplus-gdo
  project_version: "2.0.0"

  # Hardware pins
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO2
  warning_beep_pin: GPIO4
  warning_leds_pin: GPIO3
  status_led: GPIO18
  sda: GPIO16
  scl: GPIO15

  # Entity names
  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Garage Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_wireless_remote_name: Wireless Remote
  garage_sync_name: Synced
  garage_battery_name: Battery
  garage_temp_name: Garage Temp
  garage_humidity_name: Garage Humidity

  # Optional feature tuning
  garage_door_close_warning_duration: 5s
  temp_update_interval: 60s
  temp_adjust: "1.0"
  dew_point_offset: "0.0"
  blink_on_state: "true"

  # Optional package selectors (set any to ../packages/options/disabled.yaml to disable)
  network_package: ../packages/wifi-esp32.yaml
  secplus_diagnostics_package: ../packages/gdo/diagnostics.yaml
  secplus_preclose_package: ../packages/gdo/pre-close-warning.yaml
  warning_led_package: ../packages/warning-led.yaml
  buzzer_package: ../packages/buzzer-rtttl.yaml
  preclose_tones_package: ../packages/pre-close-warning-tones.yaml
  temp_sensor_package: ../packages/temp-sensor.yaml
  debug_package: ../packages/debug.yaml
  status_led_inverted: "false"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: "2026.2.0"
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

external_components:
  - source:
      type: local
      path: ../components
    components: [secplus_gdo]

packages:
  secplus_base: !include ../packages/gdo/base.yaml
  secplus_diagnostics: !include ../packages/gdo/diagnostics.yaml
  secplus_preclose: !include ../packages/gdo/pre-close-warning.yaml
  warning_led: !include ../packages/warning-led.yaml
  buzzer: !include ../packages/buzzer-rtttl.yaml
  preclose_tones: !include ../packages/pre-close-warning-tones.yaml
  status_led: !include ../packages/status-led.yaml
  temp_sensor: !include ../packages/temp-sensor.yaml
  network: !include ../packages/wifi-esp32.yaml
  debug: !include ../packages/debug.yaml

dashboard_import:
  package_import_url: github://CircuitSetup/circuitsetup-esphome/examples/advanced.yaml@master
  import_full_config: false

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

web_server:

button:
  - platform: restart
    name: Restart
    entity_category: config
