substitutions:
  name: gdo-minimal
  friendly_name: GDO Minimal
  project_name: circuitsetup.secplus-gdo
  project_version: "2.0.0"

  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO2
  status_led: GPIO18
  blink_on_state: "true"

  garage_door_cover_name: Garage Door
  garage_light_name: Garage Light
  garage_openings_name: Garage Openings
  garage_lock_name: Garage Lock
  garage_motion_name: Motion
  garage_obstruction_name: Obstruction
  garage_motor_name: Motor
  garage_button_name: Wall Button
  garage_wireless_remote_name: Wireless Remote
  garage_sync_name: Synced
  garage_battery_name: Battery

external_components:
  - source:
      type: local
      path: ../components
    components: [secplus_gdo]

packages:
  core: !include ../packages/core-esp32-s3.yaml
  network: !include ../packages/wifi-esp32.yaml
  status_led: !include ../packages/status-led.yaml
  secplus: !include ../packages/gdo/base.yaml

dashboard_import:
  package_import_url: github://CircuitSetup/circuitsetup-esphome/examples/minimal.yaml@master
  import_full_config: false

logger:
  level: INFO

api:

web_server:
