binary_sensor:
  - pin: 
      number: $wired_sensor_pin
      mode: INPUT_PULLUP
    device_class: garage_door
    id: garage_door_input
    name: Wired Sensor
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
