<<: !include garage-door-cover.yaml

# Consider the garage door open if either the optical or range sensor reports open.
# Consider the garage closed if both wired and range sensor report closed.
binary_sensor:
  - id: !extend garage_door_input
    on_state:
      - if:
          condition:
            lambda: return (x || id(garage_door_range_sensor).state);
          then:
            - cover.template.publish:
                id: garage_door
                state: OPEN
                current_operation: IDLE
          else:
            - cover.template.publish:
                id: garage_door
                state: CLOSED
                current_operation: IDLE

  - id: !extend garage_door_range_sensor
    on_state:
      - if:
          condition:
            lambda: return (x || id(garage_door_input).state);
          then:
            - cover.template.publish:
                id: garage_door
                state: OPEN
                current_operation: IDLE
          else:
            - cover.template.publish:
                id: garage_door
                state: CLOSED
                current_operation: IDLE
