binary_sensor:
  - platform: gpio
    pin: D9
    name: Garage Door (wired contact)
    device_class: garage_door
    id: garage_door_wired_sensor

cover:
  - platform: template
    name: Garage Door
    device_class: garage
    lambda: |-
      if (id(garage_door_wired_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - button.press: garage_door_opener_button
    close_action:
      - light.turn_on:
          id: led_light
          effect: strobe
      - light.turn_on:
          id: buzzer
          effect: strobe
      - delay: 5s
      - button.press: garage_door_opener_button
    stop_action:
      - button.press: garage_door_opener_button
    on_closed:
      - light.turn_off: led_light
      - light.turn_off: buzzer