sensor:
  - platform: vl53l0x
    name: Range
    update_interval: 5s
    long_range: true
    accuracy_decimals: 2
    id: range_sensor
    on_value_range:
      - below: !lambda "return id(open_distance).state + 0.1"
        above: !lambda "return id(open_distance).state - 0.1"
        then:
          - binary_sensor.template.publish:
              id: garage_door_range_sensor
              state: ON
      - above: !lambda "return id(open_distance).state + 0.1"
        then:
          - binary_sensor.template.publish:
              id: garage_door_range_sensor
              state: OFF

number:
  - platform: template
    name: Open garage door distance from device
    id: open_distance
    min_value: 0
    max_value: 2.0
    step: 0.01
    restore_value: true
    optimistic: true

binary_sensor:
  - platform: template
    name: Garage Door (range sensor)
    id: garage_door_range_sensor
