wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

improv_serial:

captive_portal:

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    id: wifi_signal_db
    entity_category: diagnostic

  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: Signal %
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: diagnostic
  
    
