name: Build
on: push
jobs:
  build-upload:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ESPHome
        run: | 
          pip3 install wheel
          pip3 install esphome
          echo "esphome_version=$(esphome version) >> $GITHUB_OUTPUT"
          mkdir assets
      
      - id: alarm-panel-esp8266-version
        uses: jbutcher5/read-yaml@main
        with:
          file: '../../alarm-panel-esp8266.yaml'
          key-path: '["substitutions", "project_version"]'

      - id: alarm-panel-pro-esp32-version
        uses: jbutcher5/read-yaml@main
        with:
          file: '../../alarm-panel-pro-esp32.yaml'
          key-path: '["substitutions", "project_version"]'

      - id: garage-door-esp8266-version
        uses: jbutcher5/read-yaml@main
        with:
          file: '../../garage-door-esp8266.yaml'
          key-path: '["substitutions", "project_version"]'

      - name: Build Alarm Panel ESP8266
        id: build-alarm-panel-esp8266
        run: | 
          esphome compile release/alarm-panel-esp8266.yaml
          build_path=release/.esphome/build/alarm-panel/.pioenvs/alarm-panel
          fname=esphome-alarm-panel-esp8266-${{ steps.alarm-panel-esp8266-version.outputs.data }}.bin
          cp $build_path/firmware-factory.bin assets/$fname
          
      - name: Build Alarm Panel ESP32 (WiFi)
        id: build-alarm-panel-pro-esp32-wifi
        run: |
          esphome compile release/alarm-panel-pro-esp32-wifi.yaml
          build_path=release/.esphome/build/alarm-panel-pro/.pioenvs/alarm-panel-pro
          fname=esphome-alarm-panel-pro-esp32-wifi-${{ steps.alarm-panel-pro-esp32-version.outputs.data }}.bin
          cp $build_path/firmware-factory.bin assets/$fname

      - name: Build Alarm Panel ESP32 (LAN8720)
        id: build-alarm-panel-pro-esp32-lan8720
        run: |
          esphome compile release/alarm-panel-pro-esp32-lan8720.yaml
          build_path=release/.esphome/build/alarm-panel-pro/.pioenvs/alarm-panel-pro
          fname=esphome-alarm-panel-pro-esp32-lan8720-${{ steps.alarm-panel-pro-esp32-version.outputs.data }}.bin
          cp $build_path/firmware-factory.bin assets/$fname

      - name: Build Alarm Panel ESP32 (RTL8201)
        id: build-alarm-panel-pro-esp32-rtl8201
        run: |
          esphome compile release/alarm-panel-pro-esp32-rtl8201.yaml
          build_path=release/.esphome/build/alarm-panel-pro/.pioenvs/alarm-panel-pro
          fname=esphome-alarm-panel-pro-esp32-rtl8201-${{ steps.alarm-panel-pro-esp32-version.outputs.data }}.bin
          cp $build_path/firmware-factory.bin assets/$fname

      - name: Build Garage Door ESP8266
        id: build-garage-door-esp8266
        run: |
          esphome compile garage-door-esp8266.yaml
          build_path=.esphome/build/garage-door/.pioenvs/garage-door
          fname=esphome-garage-door-esp8266-${{ steps.garage-door-esp8266-version.outputs.data }}.bin
          cp $build_path/firmware-factory.bin assets/$fname
      
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Upload Builds
        with:
          command: cp
          source: assets/
          destination: s3://konnected-io/builds/esphome/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --recursive --acl public-read
